<?php

// @generated — run bin/generate-route-constants.php to regenerate
// Do not edit this file manually.

declare(strict_types=1);

namespace App\Route;

/**
 * Route name constants for IDE autocomplete support.
 *
 * @generated Run `php bin/generate-route-constants.php` to regenerate after
 *            modifying config/routes.php.
 */
final class RouteNames
{
    public const string HEALTH_INDEX = 'health.index';
    public const string HEALTH_DETAILED = 'health.detailed';
    public const string HEALTH_VERSION = 'health.version';
    public const string AUTH_LOGIN = 'auth.login';
    public const string AUTH_USER = 'auth.user';
    public const string SCHOOLS_LIST = 'schools.list';
    public const string SCHOOLS_SHOW = 'schools.show';
    public const string SCHOOLS_CREATE = 'schools.create';
    public const string SCHOOLS_UPDATE = 'schools.update';
    public const string SCHOOLS_DELETE = 'schools.delete';
    public const string CLASSES_LIST = 'classes.list';
    public const string CLASSES_SHOW = 'classes.show';
    public const string CLASSES_CREATE = 'classes.create';
    public const string CLASSES_UPDATE = 'classes.update';
    public const string CLASSES_DELETE = 'classes.delete';
    public const string GROUPS_LIST = 'groups.list';
    public const string GROUPS_SHOW = 'groups.show';
    public const string GROUPS_CREATE = 'groups.create';
    public const string GROUPS_UPDATE = 'groups.update';
    public const string GROUPS_DELETE = 'groups.delete';
    public const string GROUPS_ADD_MEMBER = 'groups.addMember';
    public const string GROUPS_REMOVE_MEMBER = 'groups.removeMember';
    public const string GROUPS_ADD_CLASS = 'groups.addClass';
    public const string GROUPS_REMOVE_CLASS = 'groups.removeClass';
    public const string STUDENTS_LIST = 'students.list';
    public const string STUDENTS_SHOW = 'students.show';
    public const string STUDENTS_CREATE = 'students.create';
    public const string STUDENTS_DELETE = 'students.delete';
    public const string TEACHERS_LIST = 'teachers.list';
    public const string TEACHERS_SHOW = 'teachers.show';
    public const string TEACHERS_CREATE = 'teachers.create';
    public const string TEACHERS_DELETE = 'teachers.delete';
    public const string USERS_SEARCH = 'users.search';
    public const string METRICS_INDEX = 'metrics.index';
    public const string METRICS_RESET = 'metrics.reset';
    public const string METRICS_DASHBOARD = 'metrics.dashboard';
    public const string ALERTS_STATUS = 'alerts.status';
}
